"""Regenerate the ecc-router skill index from .claude/skill-library/*/SKILL.md.

The router's SKILL.md carries a compact index (one short line per skill) between
the index markers, so consulting it stays cheap; the full descriptions go to
index-full.md next to it, which the router greps instead of loading.
Run after adding, removing, or editing a library skill:
    .venv/Scripts/python scripts/build_skill_index.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIBRARY = ROOT / ".claude" / "skill-library"
ROUTER = ROOT / ".claude" / "skills" / "ecc-router"
START, END = "<!-- index:start -->", "<!-- index:end -->"
HOOK_CHARS = 60
BLOCK_SCALARS = {">", ">-", ">+", "|", "|-", "|+"}


def description(skill_md: Path) -> str:
    lines = skill_md.read_text(encoding="utf-8", errors="replace").splitlines()
    if not lines or lines[0].strip() != "---":
        return ""
    value, collecting = [], False
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if collecting:
            if line[:1] in (" ", "\t"):
                value.append(line.strip())
                continue
            break
        if line.startswith("description:"):
            first = line.split(":", 1)[1].strip()
            collecting = True
            if first not in BLOCK_SCALARS:
                value.append(first)
    return " ".join(" ".join(value).split()).strip("'\"")


def hook(desc: str) -> str:
    text = re.sub(r"^(This skill should be used when |Use (this skill )?(to|when) )?"
                  r"(the user (asks|wants) (to |for |about )?)?", "", desc)
    first = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0].rstrip(".")
    first = first[:1].upper() + first[1:]
    if len(first) <= HOOK_CHARS:
        return first
    return first[:HOOK_CHARS].rsplit(" ", 1)[0].rstrip(",;:-– ") + "…"


def skills() -> list:
    return [(p.parent.name, description(p)) for p in sorted(LIBRARY.glob("*/SKILL.md"))]


def render(router_text: str, entries: list) -> tuple:
    """Return (router SKILL.md with a fresh index block, index-full.md text)."""
    start = router_text.index(START) + len(START)
    end = router_text.index(END)
    block = "\n".join([
        "<!-- Generated by scripts/build_skill_index.py from each skill's frontmatter;"
        " rerun it after changing the library instead of editing these lines. -->",
        f"{len(entries)} skills. Full descriptions: `index-full.md` in this folder.",
        "",
        *(f"- `{name}` — {hook(desc)}" for name, desc in entries),
    ])
    full = "\n".join([
        "# ECC skill index: full descriptions",
        "",
        "Generated by scripts/build_skill_index.py. Grep this file for task keywords;"
        " don't load it whole.",
        "",
        *(f"- `{name}` — {desc}" for name, desc in entries),
        "",
    ])
    return router_text[:start] + "\n" + block + "\n" + router_text[end:], full


def main():
    entries = skills()
    router = ROUTER / "SKILL.md"
    text, full = render(router.read_text(encoding="utf-8"), entries)
    router.write_text(text, encoding="utf-8", newline="\n")
    (ROUTER / "index-full.md").write_text(full, encoding="utf-8", newline="\n")
    print(f"{len(entries)} skills; SKILL.md is {router.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
